# Generated by Django 4.1.5 on 2023-01-31 06:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rolename', models.CharField(choices=[('staff', 'Staff'), ('customer', 'Customer')], default='staff', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=250)),
                ('companyname', models.CharField(max_length=250)),
                ('businessphonne', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=10)),
                ('message', models.TextField(max_length=3000)),
                ('created_at', models.DateField()),
                ('updated_at', models.DateField()),
                ('roleid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Contact.role')),
            ],
        ),
    ]
